name: Workflow Evento
on:
  schedule:
    - cron: '0/2 * * * *' # Executa a cada 2 minutos
jobs:
  teste:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Action de Teste
        run: |
          echo "Actions executado apens em main e features"
      - name: Alteração no Card
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'Ação executada com sucesso!'
            })
    
