name: Workflow Evento
on:
  schedule:
    - cron: '0/2 * * * *' # Executa a cada 12 horas
  # pull_request: 
  #   branches:
  #     - main
  #   types: #Indica quando os jobs irão ser desparados no pull request
  #     - closed

  #push:
    #branches: ## - Trigger por branches
     # - main
      #- feature/*
    #tags: ## - Trigger por tags
     # - 'v*'
    # branches:
    #   - main
    #   - feature/*
  # workflow_dispatch:
  #   inputs:
  #     exemplo-input:
  #       type: string
  #       description: "Um teste de Input"
  #       required: true
jobs:
  teste:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Action de Teste
        run: |
          echo "Actions executado apens em main e features"
    
