name: Workflow Evento
on:
  pull_request: 
    branches:
      - main

  #push:
    #branches: ## - Trigger por branches
     # - main
      #- feature/*
    #tags: ## - Trigger por tags
     # - 'v*'
    # branches:
    #   - main
    #   - feature/*
  # workflow_dispatch:
  #   inputs:
  #     exemplo-input:
  #       type: string
  #       description: "Um teste de Input"
  #       required: true
jobs:
  teste:
    runs-on: ubuntu-latest
    steps:
      - name: Action de Teste
        run: |
          echo "Actions executado apens em main e features"
      - name: Alteração no Card
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'Ação executada com sucesso!'
            })
    
