name: Workflow Evento
on:
  workflow_dispatch:
    inputs:
      exemplo-input:
        type: string
        description: "Um teste de Input"
        required: true
jobs:
  teste:
    runs-on: ubuntu-latest
    steps:
      - name: Action de Teste
        run: |
          echo "Disparou o evento com input: ${{inputs.exemplo-input}}"
    
